parameters:
#    evalfor_user.example.class: Evalfor\UserBundle\Example

services:
#    evalfor_user.example:
#        class: %evalfor_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     evalfor_user.registration.form.type:
         class: Evalfor\UserBundle\Form\Type\RegistrationFormType
         arguments: [%fos_user.model.user.class%]
         tags:
             - { name: form.type, alias: evalfor_user_registration }
     evalfor_user.change_password.form.type:
        class: Evalfor\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: evalfor_user_change_password }
     evalfor_user.profile.form.type:
        class: Evalfor\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: evalfor_user_profile }
